language: rust

sudo: required

rust:
  - 1.41.1
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - echo 'Installing mylint'
  - cargo install --git https://github.com/doyoubi/mylint-rs --tag v1.0
  - echo 'Installing rustfmt'
  - rustup component add rustfmt
  - echo 'Installing clippy'
  - rustup component add clippy

script:
  - cargo build --verbose --all
  - find src -name "*.rs" | xargs rustup run stable rustfmt
  - cargo clippy -- -W clippy::indexing_slicing
  - mylint -s Expect -s IndexExpression
  - cargo test --verbose --all

notifications:
  email: false
