language: rust

sudo: required

rust:
  - 1.43.1
  - stable

matrix:
  fast_finish: true

# Using cache will block the task:
#   https://travis-ci.community/t/builds-timeout-during-or-shortly-after-creating-directory-home-travis-cache-sccache/5001
# cache:
#   cargo: true

install:
  - echo 'Installing mylint'
  - cargo install --git https://github.com/doyoubi/mylint-rs --tag v1.0
  - echo 'Installing rustfmt'
  - rustup component add rustfmt
  - echo 'Installing clippy'
  - rustup component add clippy

script:
  - cargo build --verbose --all
  - find src -name "*.rs" | xargs rustup run stable rustfmt
  - find tests -name "*.rs" | xargs rustup run stable rustfmt
  - cargo clippy -- -W clippy::indexing_slicing
  - mylint -s Expect -s IndexExpression
  - cargo test --verbose --all

notifications:
  email: false
