[package]
name = "undermoon"
version = "0.1.3"
authors = ["doyoubi"]
edition = "2018"

[[bin]]
name="server_proxy"
path="src/bin/server_proxy.rs"

[[bin]]
name="coordinator"
path="src/bin/coordinator.rs"

[[bin]]
name="mem_broker"
path="src/bin/mem_broker.rs"

[dependencies]
bytes = "0.5.4"
tokio = { version = "0.2.11", features = ["full"] }
tokio-util = { version = "0.2", features = ["full"] }
futures01 = "0.1.29"
futures = { version = "0.3.4", features = ["compat"] }
futures-timer = "3.0.1"
atomic-option = "0.1"
crc16 = "0.4.0"
crc64 = "1.0.0"
caseless = "0.2.1"
arc-swap = "0.3.11"
reqwest = { version = "0.10.1", features = ["json"] }
serde = "1.0"
serde_derive = "1.0.88"
serde_json = "1.0"
log = "0.4"
env_logger = "0.6.0"
scopeguard = "1.0.0"
itertools = "0.8.0"
futures-batch = "0.6.0"
config = "0.9"
btoi = "0.4.0"
crossbeam = "0.7.1"
crossbeam-channel = "0.3"
chashmap = "2.2.2"
actix-web = "0.7"
chrono = "0.4"
arr_macro = "0.1.2"
atoi = "0.3.1"
zstd = "0.4"
memchr = "2.3.0"
pin-project = "0.4"
string-error = "0.1.0"

[profile.release]
debug = true
lto = true
