address = "127.0.0.1:5299"
announce_address = "127.0.0.1:5299"

# If this server proxy has one and only one cluster set,
# server proxy will automatically set the cluster to default without
# needing to send AUTH command.
# This is for those clients or proxies like corvus which do not support AUTH.
auto_select_cluster = true

slowlog_len = 1024

# In microseconds like redis.
slowlog_log_slower_than = 20000

thread_number = 2

session_channel_size = 4096
backend_channel_size = 4096

backend_conn_num = 4

# Batching syscall
backend_batch_min_time = 20000
backend_batch_max_time = 400000
backend_batch_buf = 10
session_batch_min_time = 20000
session_batch_max_time = 400000
session_batch_buf = 10
