version: '3'
services:
  server_proxy:
    build:
      context: ../
      dockerfile: examples/Dockerfile-undermoon
    volumes:
    - ${PWD}/examples/multi-redis/server_proxy.toml:/undermoon/config/server_proxy.toml
    command: /undermoon/target/debug/server_proxy config/server_proxy.toml
    ports:
    - "5299:5299"
    environment:
    - RUST_LOG=undermoon=debug,server_proxy=debug
    depends_on:
    - "redis1"
    - "redis2"
    - "redis3"
  init_script:
    image: "redis"
    volumes:
    - ${PWD}/examples/multi-redis/init.sh:/init.sh
    command: /init.sh
    depends_on:
    - "redis1"
    - "redis2"
    - "redis3"
  redis1:
    container_name: redis1
    image: "redis"
    ports:
    - "7001:6379"
  redis2:
    container_name: redis2
    image: "redis"
    ports:
    - "7002:6379"
  redis3:
    container_name: redis3
    image: "redis"
    ports:
    - "7003:6379"
