version: '3'
services:
  checker:
    image: python:3.7
    volumes:
    - ${PWD}/examples/failover/requirements.txt:/checker/requirements.txt
    - ${PWD}/examples/failover/checker.py:/checker/checker.py
    - ${PWD}/examples/failover/run_checker.sh:/checker/run_checker.sh
    command: bash /checker/run_checker.sh
    depends_on:
    - "server_proxy1"
    - "server_proxy2"
    - "server_proxy3"
